name: Lighthouse Performance Test

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Run Lighthouse Performance Test and Generate JSON Report
        run: |
          npx lighthouse https://www.kevin-sauvage.com/ --quiet --output json --output-path lighthouse-report.json --chrome-flags="--headless"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lighthouse-report.json

      - name: Get Artifact url
        id: artifact_url
        run: |
          ARTIFACT_URL=$(gh api -H "Accept: application/vnd.github+json" \
                             -H "X-GitHub-Api-Version: 2022-11-28" \
                             /repos/${{ github.repository }}/actions/artifacts/${{ github.run_id }} \
                       | jq -r '.url')
          echo "artifact_url=$ARTIFACT_URL" >> "$GITHUB_OUTPUT"

      - name: Publish Lighthouse Report Link
        uses: actions/github-script@v6
        with:
          script: |
            console.log("steps: ${{ steps.artifact_url }}")
            const artifactURL = "${{ steps.artifact_url.outputs.artifact_url }}";
            const cdpURL = `chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=${encodeURIComponent(artifactURL)}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Open the Lighthouse Report in Chrome DevTools: [Open DevTools](${cdpURL})
                    URL : ${cdpURL}`
            })
