name: Lighthouse Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Run Lighthouse Performance Test
        run: npx lighthouse https://www.kevin-sauvage.com/ --quiet --output json --output-path lighthouse-report.json --chrome-flags="--headless"
        env:
          CI: true

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lighthouse-report.json

      - name: Get Lighthouse Report Content
        id: get-report-content
        run: echo "::set-output name=content::$(cat lighthouse-report.json)"

      - name: Post Lighthouse Report Comment
        if: always()
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "body": "Lighthouse Performance Report\n```\n'"${{ steps.get-report-content.outputs.content }}"'\n```"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
